on:
  pull_request:
    types:
      - opened
      - edited
jobs:
  training-testing:
    name: Training and Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Rasa Train and Test GitHub Action
        uses: RasaHQ/rasa-train-test-gha@main
        with:
          rasa_version: '3.3.0'
          data_validate: true
          rasa_train: true
          cross_validation: false
          rasa_test: true
          test_type: all
          publish_summary: true
          github_token: ${{ secrets.RASA_TOKEN }}
      - name: Install Commitizen
        run: pip install -U Commitizen
      - name: Set Version
        id: commitizen-version
        run: |
          echo "COMMITIZEN_VER=`cz version -p`" >> $GITHUB_OUTPUT
      - name: Echo Current Version
        run: |
          echo "The current version is: ${{env.COMMITIZEN_VER}}"
      - name: Move file to commitizen version
        run: |
          mv models/* models/model_{{ steps.commitizen-version.outputs.COMMITIZEN_VER }}.tar.gz
      - name: Upload model
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@master
        with:
          name: model_${{ steps.commitizen-version.outputs.COMMITIZEN_VER }}.tar.gz
          path: models