jobs:
  training-testing:
    name: Training and Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Rasa Train and Test GitHub Action
        uses: RasaHQ/rasa-train-test-gha@main
        with:
          requirements_file: requirements.txt
          data_validate: true
          rasa_train: true
          cross_validation: true
          rasa_test: true
          test_type: all
          publish_summary: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set Version
        id: commitizen-version
        run: echo "COMMITIZEN_VER=`cz version -p`" >> $GITHUB_OUTPUT
      - name: Move file to commitizen version
        run: mv models/* models/model_{{ steps.commitizen-version.outputs.COMMITIZEN_VER }}.tar.gz
      - name: Upload model
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@master
        with:
          name: model_${{ steps.commitizen-version.outputs.COMMITIZEN_VER }}.tar.gz
          path: models